version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:lts
  working_directory: ~/jopijs
restore_cache: &restore_cache
  restore_cache:
    keys:
      - v3-dependencies-{{ checksum "package.json" }}
      - v3-dependencies-
save_cache: &save_cache
  save_cache:
    paths:
      - ./node_modules
    key: v3-dependencies-{{ checksum "package.json" }}

jobs:
  Check-Dependencies:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_cache
      - run: yarn install
      - <<: *save_cache
  Link:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_cache
      - run:
          name: Link dependencies
          command: |
            yarn bootstrap
      - <<: *save_cache
  Build_Test:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_cache
      - run:
          name: Build packages and test
          command: |
            yarn test
      - <<: *save_cache
  Deliver:
    <<: *defaults
    steps:
      - run:
          name: Versioning
          command: |
            echo 'Creating versions'
  Deploy:
    <<: *defaults
    steps:
      - run:
          name: Publish packages
          command: |
            echo 'Publishing packages'

workflows:
  version: 2
  Lerna:
    jobs:
      - Check-Dependencies
      - Link:
          requires:
            - Check-Dependencies
      - Build_Test:
          requires:
            - Link
      - Deliver:
          filters:
            branches:
              only: master
          requires:
            - Build_Test
      - Deploy:
          filters:
            branches:
              only: master
          requires:
            - Deliver
