version: 2.1
jobs:
  Check-Dependencies:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  Link:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Link dependencies
          command: |
            yarn bootstrap
  Build_Test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Build packages and test
          command: |
            yarn test
  Deliver:
    docker:
      - image: circleci/node:lts
    steps:
      - run:
          name: Versioning
          command: |
            echo 'Creating versions'
  Deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - run:
          name: Publish packages
          command: |
            echo 'Publishing packages'

workflows:
  version: 2
  Lerna:
    jobs:
      - Check-Dependencies
      - Link:
          requires:
            - Check-Dependencies
      - Build_Test:
          requires:
            - Link
      - Deliver:
          filters:
            branches:
              only: master
          requires:
            - Build_Test
      - Deploy:
          filters:
            branches:
              only: master
          requires:
            - Deliver
