version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:lts
  working_directory: ~/jopijs
restore_modules_cache: &restore_modules_cache
  restore_cache:
    keys:
      - v3-dependencies-{{ checksum "package.json" }}
      - v3-dependencies-
save_modules_cache: &save_modules_cache
  save_cache:
    paths:
      - ./node_modules
    key: v3-dependencies-{{ checksum "package.json" }}

jobs:
  Check_Build_Test:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_modules_cache
      - run:
          name: Install dependencies
          command: |
            yarn install
      - run:
          name: Link dependencies
          command: |
            yarn bootstrap
      - run:
          name: Build packages and test
          command: |
            yarn test
      - <<: *save_modules_cache
  Deliver:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_modules_cache
      - run:
          name: GH user
          command: |
            git config --global user.email $GITHUB_EMAIL && git config --global user.name $GITHUB_USER
      - run:
          name: Create new version
          command: |
            $(yarn bin)/lerna version prepatch --yes
      - <<: *save_modules_cache
  Deploy:
    <<: *defaults
    steps:
      - run:
          name: Publish packages
          command: |
            echo 'Publishing packages'

workflows:
  version: 2
  Lerna:
    jobs:
      - Check_Build_Test
      - Deliver:
          filters:
            branches:
              only: master
          requires:
            - Check_Build_Test
      - Deploy:
          filters:
            branches:
              only: master
          requires:
            - Deliver
