orbs:
  release-workflows: hutson/library-release-workflows@4.3.3
version: 2.1
workflows:
  build_test_deploy:
    jobs:
      - node_10_test_plan
      - release-workflows/lerna-deliver:
          context: github-interaction
          email: eulke@navent.com
          filters:
            branches:
              only: master
          fingerprint: '61:87:86:ed:16:8f:5c:53:98:6a:5a:7c:8d:e7:ee:94'
          fullname: Esteban Ulke
          requires:
            - node_10_test_plan
      - release-workflows/lerna-deploy:
          context: npm-interaction
          filters:
            branches:
              only: master
          requires:
            - release-workflows/lerna-deliver
  version: 2
