version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn bootstrap
      - run: yarn test
      # - run: >-
      #    git config --global user.email "<<parameters.email>>" && git config
      #    --global user.name "<<parameters.fullname>>"
      #- run: $(yarn bin)/lerna version prepatch --yes
      #- run: $(yarn bin)/lerna publish from-git --yes
